version: '3.5'

services:
  postgres:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "54321:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

