/** @type {import('tailwindcss').Config} */
export default {
    darkMode: ['class'],
    content: [
        './pages/**/*.{ts,tsx}',
        './components/**/*.{ts,tsx}',
        './app/**/*.{ts,tsx}',
        './src/**/*.{ts,tsx}',
        './packages/ui-kit/src/**/*.{ts,tsx}',
    ],
    theme: {
        screens: {
            sm: '640px',
            md: '768px',
            lg: '1024px',
            xl: '1280px',
            '2xl': '1536px',
        },
        colors: {
            primary: {
                900: '#0C008C',
                800: '#1D0EBE',
                700: '#3525E6',
                600: '#4D3DF7',
                500: '#5D55FA',
                400: '#7069FA',
                300: '#8888FC',
                200: '#A2A5FC',
                100: '#C4C6FF',
                50: '#E6E6FF',
            },
            secondary: {
                900: '#014D40',
                800: '#0C6B58',
                700: '#147D64',
                600: '#199473',
                500: '#27AB83',
                400: '#3EBD93',
                300: '#65D6AD',
                200: '#8EEDC7',
                100: '#C6F7E2',
                50: '#EFFCF6',
            },
            text: {
                900: '#102A43',
                800: '#243B53',
                700: '#334E68',
                600: '#486581',
                500: '#627D98',
                400: '#829AB1',
                300: '#9FB3C8',
                200: '#BCCCDC',
                100: '#D9E2EC',
                50: '#F0F4F8',
            },
            info: {
                900: '#035388',
                800: '#0B69A3',
                700: '#127FBF',
                600: '#1992D4',
                500: '#2BB0ED',
                400: '#40C3F7',
                300: '#5ED0FA',
                200: '#81DEFD',
                100: '#B3ECFF',
                50: '#E3F8FF',
            },
            warning: {
                900: '#8D2B0B',
                800: '#B44D12',
                700: '#CB6E17',
                600: '#DE911D',
                500: '#F0B429',
                400: '#F7C948',
                300: '#FADB5F',
                200: '#FCE588',
                100: '#FFF3C4',
                50: '#FFFBEA',
            },
            error: {
                900: '#610316',
                800: '#8A041A',
                700: '#AB091E',
                600: '#CF1124',
                500: '#E12D39',
                400: '#EF4E4E',
                300: '#F86A6A',
                200: '#FF9B9B',
                100: '#FFBDBD',
                50: '#FFE3E3',
            },
        },
        container: {
            center: true,
            padding: '2rem',
            screens: {
                '2xl': '1400px',
            },
        },
        extend: {
            colors: {
                border: 'hsl(var(--border))',
                input: 'hsl(var(--input))',
                ring: 'hsl(var(--ring))',
                background: 'hsl(var(--background))',
                foreground: 'hsl(var(--foreground))',
                primary: {
                    DEFAULT: 'hsl(var(--primary))',
                    foreground: 'hsl(var(--primary-foreground))',
                },
                secondary: {
                    DEFAULT: 'hsl(var(--secondary))',
                    foreground: 'hsl(var(--secondary-foreground))',
                },
                destructive: {
                    DEFAULT: 'hsl(var(--destructive))',
                    foreground: 'hsl(var(--destructive-foreground))',
                },
                muted: {
                    DEFAULT: 'hsl(var(--muted))',
                    foreground: 'hsl(var(--muted-foreground))',
                },
                accent: {
                    DEFAULT: 'hsl(var(--accent))',
                    foreground: 'hsl(var(--accent-foreground))',
                },
                popover: {
                    DEFAULT: 'hsl(var(--popover))',
                    foreground: 'hsl(var(--popover-foreground))',
                },
                card: {
                    DEFAULT: 'hsl(var(--card))',
                    foreground: 'hsl(var(--card-foreground))',
                },
            },
            borderRadius: {
                lg: 'var(--radius)',
                md: 'calc(var(--radius) - 2px)',
                sm: 'calc(var(--radius) - 4px)',
            },
            keyframes: {
                'accordion-down': {
                    from: { height: 0 },
                    to: { height: 'var(--radix-accordion-content-height)' },
                },
                'accordion-up': {
                    from: { height: 'var(--radix-accordion-content-height)' },
                    to: { height: 0 },
                },
            },
            animation: {
                'accordion-down': 'accordion-down 0.2s ease-out',
                'accordion-up': 'accordion-up 0.2s ease-out',
            },
        },
    },
    plugins: [require('tailwindcss-animate')],
};
